version: '3.8'

services:
  web:
    image: jondumea9/devops-challenge:latest
    container_name: devops-challenge
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
