name: Deploy To EC2 Instance

on:
  workflow_run:
    workflows: ["Build and push image to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SSH into Server and Perform Actions
        run: |
          ssh -i private_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            # Start the deploy
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-challenge:latest
            # Restart the container using the latest image
            docker stop devops-challenge || true
            docker rm devops-challenge || true
            docker run -d -p 80:3000 --name devops-challenge ${{ secrets.DOCKER_USERNAME }}/devops-challenge:latest
          '

      - name: Cleanup SSH Key
        run: rm private_key
